services:
  hbbs:
    container_name: id_server_hbbs_rustdesk
    image: rustdesk/rustdesk-server:1.1.15
    environment:
      - ALWAYS_USE_RELAY=Y
    command: hbbs
    volumes:
      - ./data:/root
    ports:
      - "21115:21115/tcp"
      - "21116:21116/tcp"
      - "21116:21116/udp"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: relay_server_hbbr_rustdesk
    image: rustdesk/rustdesk-server:1.1.15
    command: hbbr
    volumes:
      - ./data:/root
    ports:
      - "21117:21117/tcp"
      - "21119:21119/tcp"
    restart: unless-stopped

